### ISSUE TITLE
Asio, why you no timeout!?

### ISSUE THREAD

**Issue by eliaperantoni** [furrent/furrent#10]
Hey I bring bad news.
The TCP library that we're currently using, [Asio](https://think-async.com/Asio/), can be used both synchronously and asynchronously.

The sync route should, in theory, be much easier to use but there seems to be no way of setting a custom timeout. This is kind of a big problem for us because we cannot afford to lose seconds on a peer that is no longer online or that is unwilling to communicate. This is especially bad when the worker thread pool is small.

There is a `socket::set_option` method that allows interacting directly with the underlying OS socket. On POSIX compliant systems, we would be interested in changing `SO_RCVTIMEO` from [`socket.h`](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_socket.h.html). This is definitely not cross-platform and [some sources](https://stackoverflow.com/questions/291871/how-to-set-a-timeout-on-blocking-sockets-in-boost-asio#comment13026182_292438) indicate that, actually, Asio nullifies any such effort by calling back right into the socket even after it yields.

So the gist of this is:
- There isn't really an alternative to Asio. It's the most popular networking library in C++ by a margin and other libraries I've looked at are not necessarily more user-friendly.
- We kind of need to lower the default timeout.
- The only valid option I see is moving to async Asio which is going to be daunting but the sooner we do it, the better. I would rather move forward with the `Downloader` implementation when confident that the TCP facilities we're using are solid and aren't going to be changed in the future.

**Comment by z1ko** [comment]
After some tought i agree that the most valid option is switching to async Asio even though this nullifies part of the work done for the thread-pool if we let the work be managed by the library. Maybe we can use a multi-socket per thread approach? Where each threads manages the download of multiple async pieces. Dunno.

**Comment by eliaperantoni** [comment]
Hey @z1ko, after some research I found that async Asio is not actually that difficult and the impact is very very limited. So the worker thread pool is alive and well.

At the moment I'm working on a type that will wrap an Asio socket and provide a simplified interface with timeout support. This API, just like sync Asio, is going to be blocking and won't spawn any more threads.

**Comment by z1ko** [comment]
Ok, that's perfect then.

**Comment by eliaperantoni** [comment]
Solved by commit https://github.com/eliaperantoni/furrent/commit/24733d515f8627971b1810571b1d98117b850f90 which is scheduled to be merged by #9. See [this test](https://github.com/eliaperantoni/furrent/blob/24733d515f8627971b1810571b1d98117b850f90/test/socket.cpp#L27-L41) for an example of the timeout usage.
