### ISSUE TITLE
Result system implementation

### ISSUE THREAD

**Issue by z1ko** [furrent/furrent#11]
A good alternative to the standard std::exception, which is not well seen by me and the c++ comunity, is to copy Rust result system.
I have already experimented with a simple implementation in the #5 draft. 

```c++
template<typename R, typename E>
class Result {
  std::variant<R, E> _variant;
  /* implemetation... */
public:
  static Result ok(R result);
  static Result error(E error);
};
```
The idea is to create a custom ErrorType for each class that utilizes the Result system.

```c++

// Custom error type for chef
enum class ChefError { EatTooMuch, NotEnoughPasta, InvalidSalad };

// Result of operation
struct Dish { /* ... */ };

// Class using the result system
class Chef {
public:
  typedef Result<Dish, ChefError> Result;

  Result create_dish(int number) {
    if (number < 0) return Result::error(ChefError::InvalidSalad);
    return Result::ok(Dish{ });
  }
};
```

I have to think of a good final implementation of the Result class, one which is smart enough to not create unnecessary copies and with
a good number of static_checks. I hould like your opinion.

**Comment by nicofretti** [comment]
I really like this approach, as soon as possible I will open a new pull request for removing the actual exception in the `BencodeParser`

**Comment by eliaperantoni** [comment]
This is really cool. I'm on board with abandoning exceptions in favor of `Result`, provided that they are sufficiently ergonomic to use.
