### ISSUE TITLE
Multi file

### ISSUE THREAD

**Issue by eliaperantoni** [furrent/furrent#16]
Something that we haven't really given much thought to yet is multi-file torrents. Basically, a Torrent can either contain a single file or a list of files, each with its own path relative to a single root directory. The whole `piece` list concept is still the same, so `Downloader` is safe. But once the entire byte sequence is downloaded in a multi-file torrent, it should be treated as the concatenation of the files' bytes instead of a single one. We need to keep this in mind when designing and implementing the component that writes downloads to disk.

![torrent drawio (1)](https://user-images.githubusercontent.com/6002855/189529192-df3edfd3-c96e-42e9-a5ef-066ed0db52ec.png)

Sources:
- https://wiki.theory.org/BitTorrentSpecification#Info_in_Single_File_Mode
- https://stackoverflow.com/questions/49394045/if-torrent-contain-multiple-files-how-to-know-what-piece-correspond-to-each-fil

**Comment by z1ko** [comment]
My solution to this problem is to simply download all files in a single big file, when every piece has been downloaded then the big file is splitted in the correct files using the length and subfolder informations present in .torrent file

**Comment by eliaperantoni** [comment]
@z1ko I agree.
