### ISSUE TITLE
Logging system

### ISSUE THREAD

**Issue by z1ko** [furrent/furrent#6]
I think we should add a good logging system to better visualize the behaviour of the program, especially given its multithreaded scope which is difficult to debug.

I don't think we should write our own implementation, instead I propose one of the following:
- [spdlog](https://github.com/gabime/spdlog)
- [loguru](https://github.com/emilk/loguru)
- [plog](https://github.com/SergiusTheBest/plog)

In the past I have already used spdlog and it was very good, let me know what you think.

**Comment by eliaperantoni** [comment]
I'd say [spdlog](https://github.com/gabime/spdlog) looks easy enough to integrate and use but feel free to include whichever you prefer!

**Comment by nicofretti** [comment]
I  approve the idea so use the more confortable, `spdlog` and `plog` seems very easy to use.
